name: 'Assertible'
description: 'Run Assertible tests'
inputs:
  APIToken:
    description: 'The secret API Token to connect to your Assertible instance.'
    required: true
  ServiceID:
    description: 'The Service ID from your Assertible Web Service.'
    required: true
  Environment:
    description: 'The environment to use on Assertible to run your Web Service.'
    required: false
    default: 'production'
  EnvironmentURL:
    description: 'Run the tests against a specific URL: transient environment.'
    required: false
  Version:
    description: 'A unique textual representation of the version.'
    required: true
    default: 'v1'
outputs:
  json:
    description: 'The unique ID of the deployment on Assertible.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.APIToken }}
    - ${{ inputs.ServiceID }}
    - ${{ inputs.Environment }}
    - ${{ inputs.EnvironmentURL }}
    - ${{ inputs.Version }}
